crawlconfig/crawlconfig/urls.py
from django.conf.urls import url
from django.contrib import admin
from siteconfig import views
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

urlpatterns = [
    url(r'^accounts/login/', auth_views.login, name='login'),
    url(r'^accounts/logout/', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^admin/logout/$', auth_views.logout,
        {'next_page': '/'}),
    url(r'^admin/', admin.site.urls),
    url(r'^addsite/', views.site_add, name='site_add'),
    url(r'^editsite/search_edit', views.search_edit, name='search_edit'),       
    url(r'^editsite/', views.site_edit, name='site_edit'),
    url(r'^viewsite/site_info', views.site_info, name='site_info'),         
    url(r'^viewsite/', views.site_view, name='site_view'),
    url(r'^save_website/', views.save_website, name='save_website'),
    url(r'^uploadsites/', views.upload_sites, name='upload_sites'),
    url(r'^save_crawl_config/', views.save_crawl_config, name='save_crawl_config'),       
    url(r'^$', views.home, name='home'),    
    # url(r'^addsiteconfig/', views.crawl_config_pick, name='crawl_config_pick'),
    url(r'^addsiteconfig/edit_config_search', views.edit_config_search, name='edit_config_search'),     
    url(r'^addsiteconfig/', views.crawl_config_search, name='crawl_config_search'),
    url(r'^editsiteconfig/(?P<website_id>\d+)/$', views.edit_config, name='crawl_config_edit'), 
    url(r'^thanks/', views.thanks, name='thanks_url'),
    url(r'^schedulecrawl/queue_crawl', views.queue_crawl, name='queue_crawl'),
    url(r'^schedulecrawl/queue_crawl/', views.queue_crawl, name='queue_crawl'),
    url(r'^schedulecrawlbulk/queue_crawl', views.queue_crawl, name='queue_crawl'),
    url(r'^schedulecrawlbulk/queue_crawl/', views.queue_crawl, name='queue_crawl'),         
    url(r'^schedulecrawl/', views.schedule_crawl, name='queue_crawl'),
    url(r'^schedulecrawlbulk/', views.schedule_crawl_bulk, name='queue_crawl_bulk'),  
    url(r'^get_crawl/', views.get_crawl, name='get_crawl_config'),
    url(r'^get_crawl_data/', views.get_crawl_data, name='get_crawl_data'), 
    url(r'^handshake/', views.handshake, name='handshake'),  
    url(r'^crawlsrunning/', views.crawl_dashboard_running, name='crawls_running'),
    url(r'^crawlslastday/', views.crawl_dashboard_lastday, name='crawls_lastday'),
    url(r'^crawlslastweek/', views.crawl_dashboard_lastweek, name='crawls_lastweek'),        
    url(r'^update_crawl_status/', views.update_crawl_status, name='update_crawl_status'),
    url(r'^update_crawl_stats/', views.update_crawl_stats, name='update_crawl_stats'),
    url(r'^nodestatus/', views.crawl_node_status, name='crawl_node_status'),
    url(r'^zerocrawls/', views.crawl_zero_crawls, name='crawl_zero_crawls'),
    url(r'^indexstats/', views.elastic_index_stats, name='elastic_index_stats'),
    url(r'^downloadindexstats/', views.elastic_index_stats_download, name='elastic_index_stats_download')     
    
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Load the tokens
# views.load_sessions()

crawlconfig/siteconfig/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.postgres.fields import JSONField
from django_bulk_update.manager import BulkUpdateManager
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.

class WebSite(models.Model):
    """ Website model class """

    objects = BulkUpdateManager()
    # website URL
    website_url = models.CharField(max_length=1024, blank=False, null=False)
    # Friendly URL
    visible_url = models.CharField(max_length=1024, blank=False, null=False,
                                   unique=True)
    # Name of the site
    name = models.CharField(max_length=128, blank=False, null=False)
    # Optional tags for a site - upto 3
    tag1 = models.CharField(max_length=24, blank=True, null=True)
    tag2 = models.CharField(max_length=24, blank=True, null=True)   
    tag3 = models.CharField(max_length=24, blank=True, null=True)

    # Content-types (upto 5)
    content_type1 = models.CharField(max_length=24, blank=True, null=True)
    content_type2 = models.CharField(max_length=24, blank=True, null=True)
    content_type3 = models.CharField(max_length=24, blank=True, null=True)
    content_type4 = models.CharField(max_length=24, blank=True, null=True)
    content_type5 = models.CharField(max_length=24, blank=True, null=True)  
    
    # Last updated
    last_updated = models.DateTimeField(auto_now=True)
    # Last crawled
    last_crawled = models.DateTimeField(blank=True, null=True, default=None)
    # Last checked for crawl
    last_checked = models.DateTimeField(blank=True, null=True, default=None)
    
    def __str__(self):
        try:
            return str(self.id) + '--' + self.name.encode('utf-8', errors='replace')
        except (UnicodeEncodeError, UnicodeDecodeError), e:
            return ''

class WebSiteCrawlStats(models.Model):
    """ Crawl statistics for website """

    objects = BulkUpdateManager()
    website = models.ForeignKey(WebSite, on_delete=models.CASCADE)
    # This is the time stamp of crawl start
    crawl_started = models.DateTimeField(blank=True, null=True, default=None)
    # This is the time stamp of crawl ended
    crawl_ended = models.DateTimeField(blank=True, null=True, default=None)   
    # No of URLs downloaded
    nurls = models.IntegerField(blank=False, null=False, default=0)
    # Which node is it running ?
    crawl_node_ip = models.GenericIPAddressField(blank=False,null=True)
    # Crawl ID
    crawl_id = models.CharField(max_length=64, blank=True, null=True)
    # Error for crawl if any
    error = JSONField("Crawl Error", default={})
    last_updated = models.DateTimeField(auto_now=True)

class WebCrawlNodeStatus(models.Model):
    """ Node status for crawl nodes """

    CRAWL_STATUS = (
        ('unknown', 'UNKNOWN'),
        ('running', 'RUNNING'),
        ('finished', 'FINISHED'))
            
    objects = BulkUpdateManager()
    # Which node is it running ?
    crawl_node_ip = models.GenericIPAddressField(blank=False,null=True)
    # Which crawl is it running
    crawl_id = models.CharField(max_length=64, blank=True, null=True)
    status = models.CharField('CRAWL STATUS', max_length=32, null=False, blank=False,
                              choices=CRAWL_STATUS)
    # free memory
    memory = models.FloatField('Free Memory', default=0.0, blank=False, null=False)
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '%s - %s @ %s' % (self.crawl_node_ip, self.status, self.last_updated)

class WebSiteCrawlConfig(models.Model):
    """ WebSite Crawl Configuration - mirroring spider_config.json """
    SPIDER_TYPES = (
        ('generic', 'Generic'),
        ('path', 'Path'),
        ('pdf', 'Pdf'),
        ('click', 'Click'),
        ('pub', 'Pub'),
        ('org', 'Org')
    )

    SPIDER_CLASS = (
        ('press', 'Press'),
        ('speaker', 'Speaker')
    )

    objects = BulkUpdateManager()

    website = models.ForeignKey(WebSite, on_delete=models.CASCADE)
    spider_type = models.CharField("Spider Type",max_length=24, blank=False,
                                   null=False, choices=SPIDER_TYPES)
    # Spider sub-class for generic spiders
    spider_class = models.CharField("Spider Class", max_length=24, blank=True,
                                    null=True, default=None,
                                    choices=SPIDER_CLASS)
    # Only for generic spider
    url_patterns = models.CharField("URL Patterns", max_length=1024, blank=True, null=True)
    url_patterns_excl = models.IntegerField("URL Patterns Exclusive", default=1, null=False, blank=False)
    parse_patterns = models.CharField("Parse Patterns", max_length=512, blank=True, null=True)
    seed_urls = JSONField("Seed URLs", default={})
    # Site specific settings
    site_settings = JSONField("Site Settings", default={})
    # Spider-subclass specific settings for a site-indexed by the sub-class key
    class_settings = JSONField("Class Settings", default={})
    # Last updated
    last_updated = models.DateTimeField(auto_now=True)


class WebSiteClassConfig(models.Model):
    """ WebSite Config for generic class sub-classes """

    objects = BulkUpdateManager()

    # Spider sub-class for generic spiders
    spider_class = models.CharField("Spider Class", max_length=24, blank=True,
                                    null=True, default=None, unique=True,
                                    choices=WebSiteCrawlConfig.SPIDER_CLASS)
    settings = JSONField(default={})
    # Last updated
    last_updated = models.DateTimeField(auto_now=True)



class WebSiteCrawlSchedule(models.Model):
    """ WebSite Crawl Schedule model class """

    objects = BulkUpdateManager()

    website = models.ForeignKey(WebSite, on_delete=models.CASCADE)
    priority = models.IntegerField(default=1, null=False, blank=False,
                                   validators=[MaxValueValidator(100),
                                               MinValueValidator(1)])
    # How often to recrawl a site - in #days
    frequency = models.IntegerField(default=30, null=False, blank=False,
                                    validators=[MaxValueValidator(60),
                                                MinValueValidator(1)])
    # Enabled for regular crawl by scheduler ?
    enabled = models.BooleanField(default=False, null=False, blank=False)
    
    # Last updated
    last_updated = models.DateTimeField(auto_now=True)

class WebCrawlSessionToken(models.Model):
    """ Secure tokens for crawler sessions """

    session_token = models.CharField(max_length=64, blank=False, null=False)
    crawl_node_ip = models.GenericIPAddressField(blank=False,null=False)
    created_at = models.DateTimeField(auto_now=True)
    
class UploadDocument(models.Model):
    """ Model for uploaded files """

    objects = BulkUpdateManager()
    
    description = models.CharField(max_length=120, blank=True)
    document = models.FileField(upload_to='uploads/')
    # Optional tags to attach to each of the site
    tag1 = models.CharField(max_length=24, blank=True, null=True)
    tag2 = models.CharField(max_length=24, blank=True, null=True)   
    tag3 = models.CharField(max_length=24, blank=True, null=True)
    allow_update = models.BooleanField(default=False)
    # Extended format 
    extended_format = models.BooleanField(default=False)
    uploaded_at = models.DateTimeField(auto_now=True)

crawlconfig/siteconfig/forms.py
from django import forms
from django.forms import ModelForm
from .models import  *


class WebSiteForm(ModelForm):
    """ Model form for WebSite class """
    
    visible_url = forms.CharField(required=False)
    name = forms.CharField(required=False)
    class Meta:
        model = WebSite
        fields = ('website_url', 'visible_url', 'name')
        exclude = ['last_crawled']


class WebSiteCrawlConfigFormBasic(ModelForm):
    """ Model form for WebSiteCrawlConfigclass - Basic version (for picking website) """
    
    class Meta:
        model = WebSiteCrawlConfig
        fields = ['website']
        #widgets = {'website': forms.Select(choices=WebSite.objects.all(),
        #                      attrs={'onChange': 'selectWebsite(this)'})}


class WebSiteCrawlConfigForm(ModelForm):
    """ Model form for WebSiteCrawlConfig class """

    class Meta:
        model = WebSiteCrawlConfig
        fields = '__all__'
        widgets = {'url_patterns': forms.Textarea(attrs={'cols': 20,
                                                         'rows': 3}),
                   'parse_patterns': forms.Textarea(attrs={'cols': 20,
                                                           'rows': 3}),
                   'seed_urls': forms.Textarea(attrs={'cols': 40,
                                                      'rows': 5,
                                                      'style': 'height:100px;width:500px'}),
                   'site_settings': forms.Textarea(attrs={'cols': 20,
                                                          'rows': 5,
                                                      'style': 'height:100px'}),                                                          
                   'class_settings': forms.Textarea(attrs={'cols': 20,
                                                           'rows': 5,
                                                      'style': 'height:100px'}),                                                           
                   'spider_type': forms.Select(attrs={'style': 'width: 100px'}),
                   'spider_class': forms.Select(attrs={'style': 'width: 100px'}),                  
                   'url_patterns_excl': forms.NumberInput(attrs={'style': 'width:50px'})}
                   #'website': forms.Select(choices=WebSite.objects.all(),
                   #                       attrs={'onChange': 'selectWebsite(this)'})}                  
        

class WebSiteCrawlScheduleForm(ModelForm):
    """ Model form for WebSiteCrawlSchedule class """
    
    class Meta:
        model = WebSiteCrawlSchedule
        exclude = ['website']
        fields = '__all__'
        widgets = { 'priority': forms.NumberInput(attrs={'style': 'width:50px'}),
                    'frequency': forms.NumberInput(attrs={'style': 'width:50px'}) }
        
class DocumentForm(ModelForm):
    class Meta:
        model = UploadDocument
        fields = ('description', 'document', 'tag1', 'tag2', 'tag3', 'allow_update', 'extended_format')

crawlconfig/templates/siteconfig/crawl_dashboard.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load jsonify %}
{% load ip_to_host %}
{% block head_title %}Web Crawl Config - Crawl Dashboard{% endblock %}
{% block custom_meta_content %} <meta http-equiv="refresh" content="60" />{% endblock %}
{% block content %}
{% include "header.html" %}


<p>{{ title }}</p>
<p/>
<p/>
<p/>
{% if data_present %}
<table id="box-table-a">
  {% if end_time %}
  <thead>
  <th>#</th><th>URL</th><th>Industry</th><th>Start Time</th><th>End Time/Status</th><th>Duration</th><th>Reported Time</th><th>Downloads</th><<th>Node</th>
  {% else %}
  <th>#</th><th>URL</th><th>Industry</th><th>Start Time</th><th>Running Time</th><th>Reported Time</th><th>Downloads</th><th># URLs/hour</th><th>Node</th>
  </thead>
  {% endif %}
  <tbody>
{% for stats in statistics %}
<tr>
  <!-- crawl id: {{ stats.crawl_id }} -->
    <!-- error: {{ stats.error | jsonify }} -->
  
    <td>{{ forloop.counter }}</td>
    <td title="{{ stats.crawl_id }}">{{ stats.visible_url }}</td>
    {% if stats.industry %}
    <td>{{ stats.industry }}</td>
    {% else %}
    <td>N.A</td>
    {% endif %}
    <td style="width:180px;">{{ stats.start_time }}</td>
    {% if end_time %}
    {% if stats.end_time %}
    <td style="width:180px;">{{ stats.end_time }}</td>
    {% else %}
    <td class="{{ stats.status }}">{{ stats.status }}</td>
    {% endif %} 
    {% endif %}
    <td>{{ stats.duration }}</td>
    <td>{{ stats.reported_time }} ago</td>  
    <td>{{ stats.downloads }}</td>
    {% if running %}
     <td>{{ stats.rate }}</td>
    {% endif %}
    {% if stats.crawl_node_ip %}
    <td>{{ stats.crawl_node_ip | ip_to_host }}</td>
    {% else %}
    <td>N.A</td>
    {% endif %} 
  </tr>
  {% endfor %}
  </tbody>
</table>

{% else %}
<p style="font-color:red">
  {% if running %}
  No running crawls at present
  {% else %}
  No data to show for crawls in last 24 hours
  {% endif %}
</p>
{% endif %}

{% if running %}
<p><a href="/crawlslastday">Check stats for last 24 hours</a></p>
{% else %}
<p><a href="/crawlsrunning">Check running crawls status</a></p>
{% endif %}

{% endblock %}

crawlconfig/templates/siteconfig/crawlconfig.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head_title %}Web Crawl Config{% endblock %}
{% block content %}
{% include "header.html" %}

<script type="text/javascript">
  function selectWebsite(obj) {
  var elt = document.getElementById(obj.id);
  if (elt.selectedIndex == -1)
     return null;

  var name = elt.options[elt.selectedIndex].text;
  var url = '/editsiteconfig/' + name.split('--')[0];
  javascript:window.location=url;
  }

</script>  

  
<div class="crawlconfigform">
  <div id="login" class="crawl-popup">
    {% if site_new %}
    <h1>Adding New Crawl Configuration for - {{ website }}</h1>
    {% else %}
    <h1>Editing Crawl Configuration for - {{ website }}</h1>
    {% endif %}
    
    <form method="POST" class="crawl-config-form" action="/save_crawl_config/">
      {% csrf_token %}
      {{ crawl_config_form.as_p }}
      {{ crawl_schedule_form.as_p }}
      <button type="submit" class="form-go">Save</button>
    </form>

  </div>
</div>
{% endblock %}

crawlconfig/templates/siteconfig/crawlconfigpick.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head_title %}Web Crawl Config{% endblock %}
{% block content %}
{% include "header.html" %}

<script type="text/javascript">
  function selectWebsite(obj) {
  var elt = document.getElementById(obj.id);
  if (elt.selectedIndex == -1)
     return null;

  var name = elt.options[elt.selectedIndex].text;
  var url = '/editsiteconfig/' + name.split('--')[0];
  javascript:window.location=url;
  }

</script>
  
<div class="crawlconfigform">
  <div id="login" class="crawl-popup">
      <h1>New Crawl Configuration - Pick a Website</h1>
    <form method="POST" class="crawl-config-form">
      {% csrf_token %}
      {{ crawl_config_form.as_p }}
    </form>

  </div>
</div>
{% endblock %}

crawlconfig/templates/siteconfig/elasticstats.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head_title %}Web Crawl Config - ElasticSearch Stats{% endblock %}
{% block content %}
{% include "header.html" %}

<p>&nbsp;&nbsp;&nbsp;Index Size =>   {{ index_size }} documents</p>
<!--- <p>&nbsp;&nbsp;&nbsp;Deleted Size => {{ index_del }} documents</p> -->

{% endblock %}

crawlconfig/templates/siteconfig/multisiteinfo.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load jsonify %}
{% block head_title %}Web Crawl Config - Site Information{% endblock %}
{% block content %}
{% include "header.html" %}

<p/>
<p>
&nbsp;&nbsp;Found {{ total }} hits.
</p>

{% for site in hits %}
{% if site.name %}
<span class="definition">{{ forloop.counter }}. {{ site.name }}</span>
{% else %}
<span class="definition">{{ forloop.counter }}. (No Name)</span>
{% endif %}
<br/><br/>
<div class="siteinfo">Site Information
  <ol>
    <li>URL: <span class="url">{{ site.website_url }}</span></li>
    <li>Visible URL: <span class="url">{{ site.visible_url }}</span></li>
    <li>Last Updated: <span class="config">{{ site.last_updated }}</span></li>
    <li>Last Crawled: <span class="config">{{ site.last_crawled }}</span></li>
  </ol>
</div>

{% if site.sched_not_found %}
<div class="siteinfo">Schedule - Not Present</div><p/><p/>
{% else %}
<div class="siteinfo">Schedule
  <ol>
    <li>Frequency of crawl: <span class="config">Once in {{ site.frequency }} days</span></li>
    <li>Priority of crawl: <span class="config">{{ site.priority }}</span></li>
    <li>Automatic Schedule Enabled: <span class="config">{{ site.enabled }}</span></li>
  </ol>
</div>
{% endif %}

{% if site.config_not_found %}
<div class="siteinfo">Configuration - Not Present</div>
{% else %}
<div class="siteinfo">Configuration
  <ol>
    <li>Spider Type: <span class="config">{{ site.spider_type }}</span></li>
    <li>Seed URLs: <ul>
        {% for url in site.seed_urls %}
        <li><a href="{{ url }}" class="url">{{ url }}</a></li>
        {% endfor %}
      </ul>
    </li>
    {% if site.site_settings %}
    <li>Site Settings: <span class="data">{{ site.site_settings | jsonify }}</span></li>
    {% else %}
    <li>Site Settings: <span class="config">N.A</span></li>
    {% endif %}
    {% if site.spider_type == "generic" %}
    {% if site.url_patterns.0 != None %}
    <li>URL Patterns: <span class="data">{{ site.url_patterns | jsonify }}</span></li>
    {% if site.parse_patterns %} 
    <li>Parse Patterns: <span class="data">{{ site.parse_patterns | jsonify }}</span></li>
    {% else %}
    <li>Parse Patterns: <span class="config">N.A</span></li>    
    {% endif %}
    {% endif %} 
    {% if site.spider_class %}
    <li>Spider Class: <span class="config">{{ site.spider_class }}</span></li>
    <li>Class Settings: <span class="data">{{ site.class_settings | jsonify }}</span></li>
    {% endif %} 
    {% endif %}
  </ol>
</div>
{% endif %}
<br/><br/>
{% endfor %}

<p/>


{% endblock %}

crawlconfig/templates/siteconfig/nodestatus.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load jsonify %}
{% load ip_to_host %}
{% block head_title %}Web Crawl Config - Node Status{% endblock %}
{% block custom_meta_content %} <meta http-equiv="refresh" content="60" />{% endblock %}
{% block content %}
{% include "header.html" %}


<p>Status of Crawl Nodes</p>
<p/>
<p/>
<p/>
<table id="box-table-a">
  <thead>
  <th>#</th><th>Node IP</th><th># Running</th><th># Finished</th><th># URLs (millions)</th><th>Last Updated</th><th>Free Memory(GB)</th><th>Active?</th>
  </thead>
  <tbody>
{% for stats in node_status %}
<tr>
    <td>{{ forloop.counter }}</td>
    <td>{{ stats.node_ip | ip_to_host }}</td>
    <td>{{ stats.running }}</td>
    <td>{{ stats.finished }}</td>
    <td>{{ stats.nurls }}</td>  
    <td style="width:180px;">{{ stats.recent }}</td>
    <td>{{ stats.memory }}</td>
    {% if stats.active %}
    <td>Yes</td>
    {% else %}
    <td>No</td>
    {% endif %} 
  </tr>
{% endfor %}
<tr><td>##</td><td>TOTAL</td><td>{{ total.running }}</td><td>{{ total.finished }}</td><td>{{ total.nurls }}</td><td></td><td></td><td></td></tr>
  </tbody>
</table>

<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p style="font-size: 1pt;">Good day.</p>


{% endblock %}

crawlconfig/templates/siteconfig/searchsite.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head_title %}Web Crawl Config - Search Site{% endblock %}
{% block content %}
{% include "header.html" %}

<p/>
<p/>
<p/>

<form method="get" action="{{ action }}" style="align:center;">
  {% if multiple %}
  <input type="hidden" name="multiple" id="id_multiple" value="1" />
  {% endif %}
  &nbsp;&nbsp;Search Web Sites(Any field): <input type="text" name="q" id="id_q" value="{{ query }}"/>
  <input type="submit" value="Search" />
</form>

{% endblock %}

crawlconfig/templates/siteconfig/siteadd.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head_title %}Web Crawl Config{% endblock %}
{% block content %}
{% include "header.html" %}

<div class="crawlconfigform">
  <div id="login" class="website-popup">

    <h1>{{ add_title }}</h1>
      </li>
    </ul>
    <form method="POST" class="site-config-form" action="{{ action }}">
      {% csrf_token %}
      {{ site_add_form.as_p }}
        <input id="website_id" type="hidden" name="website_id" value="{{ website_id }}" />
        <button type="submit" class="form-go">Save</button>

    </form>
  </div>
  </div>
{% endblock %}

crawlconfig/templates/siteconfig/siteconfig.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head_title %}Web Crawl Config{% endblock %}
{% block content %}
{% include "header.html" %}

<div class="crawlconfigform">
  <div id="login" class="website-popup">

    <h1>Add a new site to crawl</h1>
    <p>Please enter website details to be crawled</p>
      </li>
    </ul>
    <form method="POST" class="site-config-form">
      {% csrf_token %}
        <label for="id_website_url">Website URL:</label> <input class="website-url" id="id_website_url" maxlength="1024" name="website_url" type="text" required /></p>
        <p>Name of the website will be auto-fetched, if left balnk</p>
      <label for="id_name">Name:</label> <input class="name" id="id_name" name="name" type="text" /></p>
          <p>Visible or friendly URL will be same as website URL, if left blank</p>
        <label for="id_visible_url">Visible URL:</label> <input class="visible-url" id="id_visible_url" name="visible_url" type="text" /></p>
        <button type="submit" class="form-go">Save</button>

      </form>
    <p>If you want to configure crawl configuration for any existing website, <a href="/crawlconfig/">Click Here</a></p>
  </div>
  </div>
{% endblock %}

crawlconfig/templates/siteconfig/siteinfo.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load jsonify %}
{% block head_title %}Web Crawl Config - Site Information{% endblock %}
{% block content %}
{% include "header.html" %}

<p/>
<p/>
<p/>
<div class="siteinfo">Site Information
  <ol>
    <li>Name: <span class="config">{{ name }}</span></li>
    <li>URL: <span class="url">{{ website_url }}</span></li>
    <li>Visible URL: <span class="url">{{ visible_url }}</span></li>
    <li>Last Updated: <span class="config">{{ last_updated }}</span></li>
    <li>Last Crawled: <span class="config">{{ last_crawled }}</span></li>
  </ol>
</div>

{% if sched_not_found %}
<div class="siteinfo">Schedule - Not Present</div><p/><p/>
{% else %}
<div class="siteinfo">Schedule
  <ol>
    <li>Frequency of crawl: <span class="config">Once in {{ frequency }} days</span></li>
    <li>Priority of crawl: <span class="config">{{ priority }}</span></li>
    <li>Automatic Schedule Enabled: <span class="config">{{ enabled }}</span></li>
  </ol>
</div>
{% endif %}

{% if config_not_found %}
<div class="siteinfo">Configuration - Not Present</div>
{% else %}
<div class="siteinfo">Configuration
  <ol>
    <li>Spider Type: <span class="config">{{ spider_type }}</span></li>
    <li>Seed URLs: <ul>
        {% for url in seed_urls %}
        <li><a href="{{ url }}" class="url">{{ url }}</a></li>
        {% endfor %}
      </ul>
    </li>
    {% if site_settings %}
    <li>Site Settings: <span class="data">{{ site_settings | jsonify }}</span></li>
    {% else %}
    <li>Site Settings: <span class="config">N.A</span></li>
    {% endif %}
    {% if spider_type == "generic" %}
    {% if url_patterns.0 != None %}
    <li>URL Patterns: <span class="data">{{ url_patterns | jsonify }}</span></li>
    {% if parse_patterns %} 
    <li>Parse Patterns: <span class="data">{{ parse_patterns | jsonify }}</span></li>
    {% else %}
    <li>Parse Patterns: <span class="config">N.A</span></li>    
    {% endif %}
    {% endif %} 
    {% if spider_class %}
    <li>Spider Class: <span class="config">{{ spider_class }}</span></li>
    <li>Class Settings: <span class="data">{{ class_settings | jsonify }}</span></li>
    {% endif %} 
    {% endif %}
  </ol>
</div>
{% endif %}
<p/>
<p/>
<p/>
<p/>
<p/>
<p/>


{% endblock %}